image: "php:7.4"

stages:
  - build
  - lint
  - check
  - deploy

build_composer:
  stage: build
  image: "php:7.4"
  before_script:
    - apt-get update && apt-get install -y libzip-dev unzip git curl && docker-php-ext-install zip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  script:
    - composer install --no-interaction --verbose
  artifacts:
    untracked: true

php-codesniffer:
  image: "php:7.4"
  stage: lint
  artifacts:
    untracked: true
  dependencies:
    - build_composer
  script:
    - ./vendor/bin/phpcs -n --extensions=php --standard=PSR12 ./Classes/

phpmd:
  image: "php:7.4"
  stage: check
  dependencies:
    - build_composer
  script:
    - php ./vendor/bin/phpmd ./Classes/ ansi ./phpmd.xml --exclude Classes/Vendor/*