image: "php:7.4"

stages:
  - build
  - lint
  - check
  - deploy

build_composer:
  stage: build
  image: "composer:latest"
  script:
    - composer install --no-interaction --verbose
  artifacts:
    untracked: true

php-codesniffer:
  image: "php:7.4"
  stage: lint
  artifacts:
    untracked: true
  dependencies:
    - build_composer
  script:
    - ./vendor/bin/phpcs -n --extensions=php --standard=PSR12 ./Classes/

phpmd:
  image: "php:7.4"
  stage: check
  artifacts:
    untracked: true
  dependencies:
    - build_composer
  script:
    - php ./vendor/bin/phpmd ./Classes/ ansi ./phpmd.xml

phpstan:
  image: "php:7.4"
  stage: check
  artifacts:
    untracked: true
  dependencies:
    - build_composer
  before_script:
    - echo "memory_limit=512M" > /usr/local/etc/php/conf.d/memory-limit.ini
  script:
    - php -d memory_limit=512M ./vendor/bin/phpstan analyze ./Classes/ --level 5